export const DEFAULT_REQUIRED_INE_FIELDS = [
  "front",
  "back",
  "nombre",
  "apellidoPaterno",
  "apellidoMaterno",
  "curp",
  "claveElector",
  "fechaNacimiento",
  "sexo",
  "seccion",
  "vigencia",
  "cic",
  "domicilio",
] as const;

export const INE_REQUIRED_FIELD_LABELS: Record<string, string> = {
  front: "Frente",
  back: "Reverso",
  ocrData: "Datos OCR",
  nombre: "Nombre(s)",
  apellidoPaterno: "Apellido paterno",
  apellidoMaterno: "Apellido materno",
  claveElector: "Clave de elector",
  ocrNumber: "OCR",
  cic: "CIC",
  curp: "CURP",
  fechaNacimiento: "Fecha de nacimiento",
  sexo: "Sexo",
  seccion: "Sección",
  registro: "Año de registro",
  vigencia: "Vigencia",
  domicilio: "Domicilio",
};
